# Data Understanding

## Objective

The objective of this notebook is to explore and understand the raw Indian Technology Jobs dataset before performing any preprocessing.

This notebook focuses on understanding the dataset's structure, quality, and characteristics. No modifications are made to the original data.

---

## Tasks

- Load the dataset
- Inspect its structure
- Examine data types
- Check missing values
- Check duplicate records
- Generate descriptive statistics
- Explore categorical variables
- Create a data dictionary
- Summarize initial observations

---

## Expected Output

A complete understanding of the dataset and its suitability for building CareerLens AI.

In [1]:
import pandas as pd
import numpy as np

# Display Settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", 1200)

In [2]:
df = pd.read_csv("../data/raw/indian_tech_jobs_2026.csv")

df.head()

   job_id                             job_title                     company_name  company_rating                       location scraped_city   role_category experience_raw  experience_min_yrs  experience_max_yrs     salary_raw  salary_min_lpa  salary_max_lpa  salary_disclosed                                                                                                                    skills_required  skills_count                                                                             job_description posted_date_raw work_mode   company_size_bucket                                                                                                    job_url data_source  scraped_at  salary_tier   experience_tier  is_senior primary_city           skill_domain  salary_midpoint_lpa  days_since_posted  is_fresher_friendly  salary_negotiable
0       1                        Data Scientist                            Cisco             4.1                      Bengaluru    Bangalore  Data Scientist       7-10 Yrs                 7.0                10.0  Not Disclosed             0.0             0.0             False  Computer science, Data analysis, data science, Supply chain operations, data visualization, Customer engagement, cisco, Analytics             8  Bachelor s degree in Statistics, Mathematics, Computer Science, Data Science, or a rela...    3+ weeks ago   On-site         Large (1000+)              https://www.naukri.com/job-listings-data-scientist-cisco-bengaluru-7-to-10-years-270326504991  naukri.com  2025-06-10  Undisclosed  Senior (6-8 Yrs)      False    Bangalore  Business Intelligence                  0.0               21.0                False              False
1       2                        Data Scientist                  Caterpillar Inc             4.1                      Bengaluru    Bangalore  Data Scientist        4-8 Yrs                 4.0                 8.0  Not Disclosed             0.0             0.0             False         Basic, Data management, Business analytics, Analytical, Machine learning, Programming, Data processing, data visualization             8  Requirements Analysis: Knowledge of tools, methods, and techniques of requirement analy...    3+ weeks ago   On-site  Small/Startup (<100)  https://www.naukri.com/job-listings-data-scientist-caterpillar-brazil-bengaluru-4-to-8-years-010526502121  naukri.com  2025-06-10  Undisclosed     Mid (3-5 Yrs)      False    Bangalore               AI/ML/DL                  0.0               21.0                False              False
2       3              Analytics Data Scientist        Foreign IT Consulting MNC             3.6  Hyderabad, Chennai, Bengaluru    Bangalore  Data Scientist        4-9 Yrs                 4.0                 9.0  Not Disclosed             0.0             0.0             False                                                                                                                      Not Available             0                                                                               Not Available   Not Available   On-site         Large (1000+)                                                                                                        NaN  naukri.com  2025-06-10  Undisclosed     Mid (3-5 Yrs)      False    Hyderabad  Business Intelligence                  0.0               21.0                False              False
3       4                        Data Scientist  Fortune 500 IT Services Company             3.6              Mumbai, Bengaluru    Bangalore  Data Scientist      10-14 Yrs                 0.0                 0.0  Not Disclosed             0.0             0.0             False                                                                                                                      Not Available             0                                                                               Not Available   Not Available   On-site  Small/Startup (<100)                                                                                                        NaN  naukri.com  2025-06-10  Undisclosed           Fresher      False       Mumbai           Data Science                  0.0               21.0                 True              False
4       5  Sr. Artificial Intelligence Engineer    Fortune 500 Product-based MNC             3.6                Pune, Bengaluru    Bangalore  Data Scientist       5-10 Yrs                 5.0                10.0  Not Disclosed             0.0             0.0             False                                                                                                                      Not Available             0                                                                               Not Available   Not Available   On-site  Small/Startup (<100)                                                                                                        NaN  naukri.com  2025-06-10  Undisclosed     Mid (3-5 Yrs)       True         Pune           Data Science                  0.0               21.0                False              False

In [3]:
rows, cols = df.shape

print("=" * 50)
print("DATASET OVERVIEW")
print("=" * 50)

print(f"Rows    : {rows:,}")
print(f"Columns : {cols}")

==================================================
DATASET OVERVIEW
==================================================
Rows    : 23,201
Columns : 32

In [4]:
columns = pd.DataFrame({
    "Column Number": range(1, len(df.columns) + 1),
    "Column Name": df.columns
})

columns

    Column Number          Column Name
0               1               job_id
1               2            job_title
2               3         company_name
3               4       company_rating
4               5             location
5               6         scraped_city
6               7        role_category
7               8       experience_raw
8               9   experience_min_yrs
9              10   experience_max_yrs
10             11           salary_raw
11             12       salary_min_lpa
12             13       salary_max_lpa
13             14     salary_disclosed
14             15      skills_required
15             16         skills_count
16             17      job_description
17             18      posted_date_raw
18             19            work_mode
19             20  company_size_bucket
20             21              job_url
21             22          data_source
22             23           scraped_at
23             24          salary_tier
24             25      experience_tier
25             26            is_senior
26             27         primary_city
27             28         skill_domain
28             29  salary_midpoint_lpa
29             30    days_since_posted
30             31  is_fresher_friendly
31             32    salary_negotiable

In [5]:
df.info

<bound method DataFrame.info of        job_id                                        job_title                     company_name  company_rating                             location scraped_city     role_category experience_raw  experience_min_yrs  experience_max_yrs     salary_raw  salary_min_lpa  salary_max_lpa  salary_disclosed                                                                                                                    skills_required  skills_count                                                                             job_description posted_date_raw work_mode   company_size_bucket                                                                                                                                                                   job_url data_source  scraped_at         salary_tier          experience_tier  is_senior primary_city           skill_domain  salary_midpoint_lpa  days_since_posted  is_fresher_friendly  salary_negotiable
0           1                                   Data Scientist                            Cisco             4.1                            Bengaluru    Bangalore    Data Scientist       7-10 Yrs                 7.0                10.0  Not Disclosed             0.0             0.0             False  Computer science, Data analysis, data science, Supply chain operations, data visualization, Customer engagement, cisco, Analytics             8  Bachelor s degree in Statistics, Mathematics, Computer Science, Data Science, or a rela...    3+ weeks ago   On-site         Large (1000+)                                                                             https://www.naukri.com/job-listings-data-scientist-cisco-bengaluru-7-to-10-years-270326504991  naukri.com  2025-06-10         Undisclosed         Senior (6-8 Yrs)      False    Bangalore  Business Intelligence                  0.0               21.0                False              False
1           2                                   Data Scientist                  Caterpillar Inc             4.1                            Bengaluru    Bangalore    Data Scientist        4-8 Yrs                 4.0                 8.0  Not Disclosed             0.0             0.0             False         Basic, Data management, Business analytics, Analytical, Machine learning, Programming, Data processing, data visualization             8  Requirements Analysis: Knowledge of tools, methods, and techniques of requirement analy...    3+ weeks ago   On-site  Small/Startup (<100)                                                                 https://www.naukri.com/job-listings-data-scientist-caterpillar-brazil-bengaluru-4-to-8-years-010526502121  naukri.com  2025-06-10         Undisclosed            Mid (3-5 Yrs)      False    Bangalore               AI/ML/DL                  0.0               21.0                False              False
2           3                         Analytics Data Scientist        Foreign IT Consulting MNC             3.6        Hyderabad, Chennai, Bengaluru    Bangalore    Data Scientist        4-9 Yrs                 4.0                 9.0  Not Disclosed             0.0             0.0             False                                                                                                                      Not Available             0                                                                               Not Available   Not Available   On-site         Large (1000+)                                                                                                                                                                       NaN  naukri.com  2025-06-10         Undisclosed            Mid (3-5 Yrs)      False    Hyderabad  Business Intelligence                  0.0               21.0                False              False
3           4                                   Data Scientist  Fortune 500 IT Services Company             3.6                    Mumbai, Bengaluru    Bangalore    Data Scientist      10-14 Yrs                 0.0                 0.0  Not Disclosed             0.0             0.0             False                                                                                                                      Not Available             0                                                                               Not Available   Not Available   On-site  Small/Startup (<100)                                                                                                                                                                       NaN  naukri.com  2025-06-10         Undisclosed                  Fresher      False       Mumbai           Data Science                  0.0               21.0                 True              False
4           5             Sr. Artificial Intelligence Engineer    Fortune 500 Product-based MNC             3.6                      Pune, Bengaluru    Bangalore    Data Scientist       5-10 Yrs                 5.0                10.0  Not Disclosed             0.0             0.0             False                                                                                                                      Not Available             0                                                                               Not Available   Not Available   On-site  Small/Startup (<100)                                                                                                                                                                       NaN  naukri.com  2025-06-10         Undisclosed            Mid (3-5 Yrs)       True         Pune           Data Science                  0.0               21.0                False              False
...       ...                                              ...                              ...             ...                                  ...          ...               ...            ...                 ...                 ...            ...             ...             ...               ...                                                                                                                                ...           ...                                                                                         ...             ...       ...                   ...                                                                                                                                                                       ...         ...         ...                 ...                      ...        ...          ...                    ...                  ...                ...                  ...                ...
23196   23197                       Python Developer-Hyderabad                          Infosys             3.5                   Hybrid - Hyderabad    Hyderabad  Python Developer        2-7 Yrs                 2.0                 7.0  Not Disclosed             0.0             0.0             False                                                                                          Django, Python, Pandas, Numpy, Flask, SQL             6                    MCA, MSc, MTech, Bachelor of Engineering, BCA, BSc, BTech . Service Line       1 day ago    Hybrid         Large (1000+)                                                                https://www.naukri.com/job-listings-python-developer-hyderabad-infosys-hyderabad-2-to-7-years-080626034957  naukri.com  2025-06-10         Undisclosed         Junior (0-2 Yrs)      False    Hyderabad           Data Science                  0.0                1.0                False              False
23197   23198                                 Python Developer                           Accufy             3.6                            Hyderabad    Hyderabad  Python Developer        0-4 Yrs                 0.0                 4.0  Not Disclosed             0.0             0.0             False                      Computer science, Backend, Version control, GIT, data science, Data modeling, Programming, Automation systems             8  . Bachelors or Masters degree in Computer Science, Engineering, AI / ML, Data Science, ...       1 day ago   On-site  Small/Startup (<100)                                                                           https://www.naukri.com/job-listings-python-developer-accufy-hyderabad-0-to-4-years-090626502768  naukri.com  2025-06-10         Undisclosed                  Fresher      False    Hyderabad           Data Science                  0.0                1.0                 True              False
23198   23199  Walk in Interview Python Developer II Hyderabad        Tata Consultancy Services             3.3  Hyderabad, Pune, Mumbai (All Areas)    Hyderabad  Python Developer         13 Jun                13.0                 8.0  Not Disclosed             0.0             0.0             False                                                                                    Python, Pyspark, SQL, Development, Interviewing             5    Role - Python DeveloperExp. - 6+ yearsWalk in Location - Hyderabad {TCS Rajapushpa Pa...          13 Jun   On-site         Large (1000+)  https://www.naukri.com/job-listings-walk-in-interview-python-developer-ii-hyderabad-tata-consultancy-services-hyderabad-pune-mumbai-all-areas-6-to-11-years-080626000881  naukri.com  2025-06-10         Undisclosed  Lead/Architect (9+ Yrs)      False    Hyderabad       Data Engineering                  0.0               21.0                False              False
23199   23200                                 Python Developer                        Mediamint             2.8                   Hybrid - Hyderabad    Hyderabad  Python Developer        3-5 Yrs                 3.0                 5.0  Not Disclosed             0.0             0.0             False                                        AI/ML, API, Python Development, Python, Python Framework, Ml, Artificial Intelligence, Aiml             8  We are looking for a skilled Python Developer with 35 years of experience in building s...           Today    Hybrid  Small/Startup (<100)                                                                        https://www.naukri.com/job-listings-python-developer-mediamint-hyderabad-3-to-5-years-280426025950  naukri.com  2025-06-10         Undisclosed            Mid (3-5 Yrs)      False    Hyderabad           Data Science                  0.0                0.0                False              False
23200   23201                                 Python Developer           CMM Level 5 IT Company             3.6                            Hyderabad    Hyderabad  Python Developer       7-12 Yrs                 7.0                12.0  10-16 Lacs PA            10.0            16.0              True                                                          API, Python Development, Python, Python Framework, Development, Framework             6  Job Title: Senior Python Developer Experience: 7+ Years Location: HyderabadJob Descript...       1 day ago   On-site  Small/Startup (<100)                                                                         https://www.naukri.com/job-listings-python-developer-experis-hyderabad-7-to-12-years-010626007733  naukri.com  2025-06-10  Senior (10-20 LPA)         Senior (6-8 Yrs)      False    Hyderabad           Data Science                 13.0                1.0                False              False

[23201 rows x 32 columns]>

In [6]:
dtype_summary = (
    df.dtypes
      .value_counts()
      .rename_axis("Data Type")
      .reset_index(name="Count")
)

dtype_summary

  Data Type  Count
0       str     19
1   float64      7
2      bool      4
3     int64      2

In [8]:
object_columns = df.select_dtypes(include="object").columns.tolist()
numeric_columns = df.select_dtypes(include=["int64", "float64"]).columns.tolist()

print("Categorical / Text Columns:")
print(object_columns)
print("Number of columns= ",len(object_columns))

print("\n" + "=" * 60 + "\n")

print("Numerical Columns:")
print(numeric_columns)
print("Number of columns= ",len(numeric_columns))

Categorical / Text Columns:
['job_title', 'company_name', 'location', 'scraped_city', 'role_category', 'experience_raw', 'salary_raw', 'skills_required', 'job_description', 'posted_date_raw', 'work_mode', 'company_size_bucket', 'job_url', 'data_source', 'scraped_at', 'salary_tier', 'experience_tier', 'primary_city', 'skill_domain']
Number of columns=  19

============================================================

Numerical Columns:
['job_id', 'company_rating', 'experience_min_yrs', 'experience_max_yrs', 'salary_min_lpa', 'salary_max_lpa', 'skills_count', 'salary_midpoint_lpa', 'days_since_posted']
Number of columns=  9

C:\Users\arush\AppData\Local\Temp\ipykernel_1604\840010303.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  object_columns = df.select_dtypes(include="object").columns.tolist()

In [9]:
missing_values = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": round((df.isnull().sum() / len(df)) * 100, 2)
})

missing_values = missing_values.sort_values(
    by="Missing Values",
    ascending=False
)

missing_values

                     Missing Values  Percentage
job_url                          53        0.23
job_id                            0        0.00
company_name                      0        0.00
job_title                         0        0.00
location                          0        0.00
scraped_city                      0        0.00
role_category                     0        0.00
company_rating                    0        0.00
experience_min_yrs                0        0.00
experience_max_yrs                0        0.00
salary_raw                        0        0.00
salary_min_lpa                    0        0.00
salary_max_lpa                    0        0.00
salary_disclosed                  0        0.00
skills_required                   0        0.00
experience_raw                    0        0.00
skills_count                      0        0.00
job_description                   0        0.00
work_mode                         0        0.00
posted_date_raw                   0        0.00
company_size_bucket               0        0.00
data_source                       0        0.00
scraped_at                        0        0.00
salary_tier                       0        0.00
experience_tier                   0        0.00
is_senior                         0        0.00
primary_city                      0        0.00
skill_domain                      0        0.00
salary_midpoint_lpa               0        0.00
days_since_posted                 0        0.00
is_fresher_friendly               0        0.00
salary_negotiable                 0        0.00

In [10]:
missing_only = missing_values[
    missing_values["Missing Values"] > 0
]

missing_only

         Missing Values  Percentage
job_url              53        0.23

In [11]:
duplicates = df.duplicated().sum()

print("=" * 50)
print("DUPLICATE RECORDS")
print("=" * 50)

print(f"Duplicate Rows: {duplicates}")

==================================================
DUPLICATE RECORDS
==================================================
Duplicate Rows: 0

In [12]:
print("=" * 50)
print("MISSING VALUE SUMMARY")
print("=" * 50)

print(f"Columns with Missing Values : {(missing_values['Missing Values'] > 0).sum()}")
print(f"Total Missing Values        : {missing_values['Missing Values'].sum()}")

==================================================
MISSING VALUE SUMMARY
==================================================
Columns with Missing Values : 1
Total Missing Values        : 53

In [15]:
numerical_summary = df.describe().T
numerical_summary

                       count          mean          std  min     25%      50%      75%      max
job_id               23201.0  11601.000000  6697.696134  1.0  5801.0  11601.0  17401.0  23201.0
company_rating       23201.0      3.586449     0.514250  1.0     3.4      3.6      3.8      5.0
experience_min_yrs   23201.0      4.135080     2.933976  0.0     2.0      4.0      6.0     25.0
experience_max_yrs   23201.0      7.829059     3.946834  0.0     5.0      8.0     10.0     31.0
salary_min_lpa       23201.0      1.383952     4.841570  0.0     0.0      0.0      0.0     85.0
salary_max_lpa       23201.0      2.271790     7.469383  0.0     0.0      0.0      0.0     90.0
skills_count         23201.0      7.604198     1.456530  0.0     8.0      8.0      8.0      8.0
salary_midpoint_lpa  23201.0      1.827872     6.109373  0.0     0.0      0.0      0.0     87.5
days_since_posted    23201.0     15.698935     7.575881  0.0     7.0     21.0     21.0     90.0

In [16]:
categorical_summary = pd.DataFrame({
    "Unique Values": df.select_dtypes(include="object").nunique(),
    "Most Frequent": df.select_dtypes(include="object").mode().iloc[0]
})

categorical_summary

C:\Users\arush\AppData\Local\Temp\ipykernel_1604\2312402402.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  "Unique Values": df.select_dtypes(include="object").nunique(),
C:\Users\arush\AppData\Local\Temp\ipykernel_1604\2312402402.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  "Most Frequent": df.select_dtypes(include="object").mode().iloc[0]

                     Unique Values                                                                                                                                                   Most Frequent
job_title                    13128                                                                                                                                                   Data Engineer
company_name                  6993                                                                                                                                       Tata Consultancy Services
location                      1565                                                                                                                                                       Bengaluru
scraped_city                    11                                                                                                                                                       Bangalore
role_category                    6                                                                                                                                                  Data Scientist
experience_raw                 238                                                                                                                                                        5-10 Yrs
salary_raw                     476                                                                                                                                                   Not Disclosed
skills_required              19185                                                                                                                                                   Not Available
job_description              18306                                                                                                                                                   Not Available
posted_date_raw                 47                                                                                                                                                    3+ weeks ago
work_mode                        3                                                                                                                                                         On-site
company_size_bucket              3                                                                                                                                            Small/Startup (<100)
job_url                      21070  https://www.naukri.com/job-listings-business-analyst-fortis-healthcare-ltd-kolkata-mumbai-new-delhi-hyderabad-pune-chennai-bengaluru-2-to-6-years-271125502182
data_source                      1                                                                                                                                                      naukri.com
scraped_at                       1                                                                                                                                                      2025-06-10
salary_tier                      6                                                                                                                                                     Undisclosed
experience_tier                  5                                                                                                                                                   Mid (3-5 Yrs)
primary_city                   198                                                                                                                                                          Mumbai
skill_domain                     5                                                                                                                                           Business Intelligence

In [17]:
df["job_title"].value_counts().head(10)

job_title
Data Engineer                847
Business Analyst             829
Data Scientist               516
Data Analyst                 404
Senior Data Engineer         245
Python Developer             218
Senior Data Scientist        175
Machine Learning Engineer    162
Azure Data Engineer          159
Senior Business Analyst      131
Name: count, dtype: int64

In [18]:
df["primary_city"].value_counts().head(10)

primary_city
Mumbai       3276
Bangalore    2830
Chennai      2666
Pune         2606
Noida        2585
Gurgaon      2210
Remote       2010
Kolkata      1735
Ahmedabad    1352
Delhi         920
Name: count, dtype: int64

In [19]:
df["work_mode"].value_counts().head(10)

work_mode
On-site    18701
Hybrid      2347
Remote      2153
Name: count, dtype: int64

In [20]:
df["skill_domain"].value_counts()

skill_domain
Business Intelligence    11124
AI/ML/DL                  6591
Cloud & DevOps            2344
Data Engineering          1595
Data Science              1547
Name: count, dtype: int64

In [21]:
data_dictionary = pd.DataFrame({

    "Column":[
        "job_title",
        "company_name",
        "company_rating",
        "experience_min_yrs",
        "experience_max_yrs",
        "salary_midpoint_lpa",
        "skills_required",
        "work_mode",
        "primary_city",
        "skill_domain"
    ],

    "Description":[
        "Job role advertised",
        "Hiring company",
        "Company rating",
        "Minimum experience required",
        "Maximum experience required",
        "Average salary (LPA)",
        "Required technical skills",
        "Remote, Hybrid or On-site",
        "Primary hiring city",
        "Primary technology domain"
    ],

    "Used In":[
        "Dashboard, Career Advisor",
        "Dashboard",
        "Analytics",
        "Career Advisor",
        "Career Advisor",
        "Salary Module",
        "Recommendation Engine",
        "Market Insights",
        "City Analytics",
        "Domain Analytics"
    ]

})

data_dictionary

                Column                  Description                    Used In
0            job_title          Job role advertised  Dashboard, Career Advisor
1         company_name               Hiring company                  Dashboard
2       company_rating               Company rating                  Analytics
3   experience_min_yrs  Minimum experience required             Career Advisor
4   experience_max_yrs  Maximum experience required             Career Advisor
5  salary_midpoint_lpa         Average salary (LPA)              Salary Module
6      skills_required    Required technical skills      Recommendation Engine
7            work_mode    Remote, Hybrid or On-site            Market Insights
8         primary_city          Primary hiring city             City Analytics
9         skill_domain    Primary technology domain           Domain Analytics

# Conclusion

In this notebook, we explored the structure and quality of the raw Indian Technology Jobs dataset.

Key activities completed:

- Loaded and inspected the dataset
- Examined dataset dimensions and feature types
- Identified missing values and duplicate records
- Generated descriptive statistics
- Explored categorical features
- Created a data dictionary
- Documented initial observations

The insights gained from this analysis will guide the data cleaning process in the next notebook.

Next Notebook:
**02_data_cleaning.ipynb**