# Data Cleaning

## Objective

The objective of this notebook is to transform the raw Indian Technology Jobs dataset into a clean, consistent, and analysis-ready dataset.

This notebook focuses only on preprocessing the data. No feature engineering, exploratory analysis, or modeling is performed.

---

## Tasks

- Load the raw dataset
- Assess data quality
- Remove duplicate records
- Handle missing values
- Clean salary columns
- Standardize text fields
- Clean and normalize skills
- Create basic preprocessing features
- Validate the cleaned dataset
- Save the cleaned dataset

---

## Expected Output

A cleaned dataset named **careerlens_cleaned.csv**, which will be used in all subsequent notebooks.

In [22]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", 1200)

In [23]:
df = pd.read_csv("../data/raw/indian_tech_jobs_2026.csv")

df.head()

   job_id                             job_title                     company_name  company_rating                       location scraped_city   role_category experience_raw  experience_min_yrs  experience_max_yrs     salary_raw  salary_min_lpa  salary_max_lpa  salary_disclosed                                                                                                                    skills_required  skills_count                                                                             job_description posted_date_raw work_mode   company_size_bucket                                                                                                    job_url data_source  scraped_at  salary_tier   experience_tier  is_senior primary_city           skill_domain  salary_midpoint_lpa  days_since_posted  is_fresher_friendly  salary_negotiable
0       1                        Data Scientist                            Cisco             4.1                      Bengaluru    Bangalore  Data Scientist       7-10 Yrs                 7.0                10.0  Not Disclosed             0.0             0.0             False  Computer science, Data analysis, data science, Supply chain operations, data visualization, Customer engagement, cisco, Analytics             8  Bachelor s degree in Statistics, Mathematics, Computer Science, Data Science, or a rela...    3+ weeks ago   On-site         Large (1000+)              https://www.naukri.com/job-listings-data-scientist-cisco-bengaluru-7-to-10-years-270326504991  naukri.com  2025-06-10  Undisclosed  Senior (6-8 Yrs)      False    Bangalore  Business Intelligence                  0.0               21.0                False              False
1       2                        Data Scientist                  Caterpillar Inc             4.1                      Bengaluru    Bangalore  Data Scientist        4-8 Yrs                 4.0                 8.0  Not Disclosed             0.0             0.0             False         Basic, Data management, Business analytics, Analytical, Machine learning, Programming, Data processing, data visualization             8  Requirements Analysis: Knowledge of tools, methods, and techniques of requirement analy...    3+ weeks ago   On-site  Small/Startup (<100)  https://www.naukri.com/job-listings-data-scientist-caterpillar-brazil-bengaluru-4-to-8-years-010526502121  naukri.com  2025-06-10  Undisclosed     Mid (3-5 Yrs)      False    Bangalore               AI/ML/DL                  0.0               21.0                False              False
2       3              Analytics Data Scientist        Foreign IT Consulting MNC             3.6  Hyderabad, Chennai, Bengaluru    Bangalore  Data Scientist        4-9 Yrs                 4.0                 9.0  Not Disclosed             0.0             0.0             False                                                                                                                      Not Available             0                                                                               Not Available   Not Available   On-site         Large (1000+)                                                                                                        NaN  naukri.com  2025-06-10  Undisclosed     Mid (3-5 Yrs)      False    Hyderabad  Business Intelligence                  0.0               21.0                False              False
3       4                        Data Scientist  Fortune 500 IT Services Company             3.6              Mumbai, Bengaluru    Bangalore  Data Scientist      10-14 Yrs                 0.0                 0.0  Not Disclosed             0.0             0.0             False                                                                                                                      Not Available             0                                                                               Not Available   Not Available   On-site  Small/Startup (<100)                                                                                                        NaN  naukri.com  2025-06-10  Undisclosed           Fresher      False       Mumbai           Data Science                  0.0               21.0                 True              False
4       5  Sr. Artificial Intelligence Engineer    Fortune 500 Product-based MNC             3.6                Pune, Bengaluru    Bangalore  Data Scientist       5-10 Yrs                 5.0                10.0  Not Disclosed             0.0             0.0             False                                                                                                                      Not Available             0                                                                               Not Available   Not Available   On-site  Small/Startup (<100)                                                                                                        NaN  naukri.com  2025-06-10  Undisclosed     Mid (3-5 Yrs)       True         Pune           Data Science                  0.0               21.0                False              False

In [24]:
print("=" * 50)
print("INITIAL DATA QUALITY CHECK")
print("=" * 50)

print(f"Rows    : {df.shape[0]:,}")
print(f"Columns : {df.shape[1]}")

print(f"\nDuplicate Rows : {df.duplicated().sum()}")

print(f"\nTotal Missing Values : {df.isnull().sum().sum()}")

==================================================
INITIAL DATA QUALITY CHECK
==================================================
Rows    : 23,201
Columns : 32

Duplicate Rows : 0

Total Missing Values : 53

In [25]:
text_columns = df.select_dtypes(include="object").columns.tolist()

print(text_columns)

['job_title', 'company_name', 'location', 'scraped_city', 'role_category', 'experience_raw', 'salary_raw', 'skills_required', 'job_description', 'posted_date_raw', 'work_mode', 'company_size_bucket', 'job_url', 'data_source', 'scraped_at', 'salary_tier', 'experience_tier', 'primary_city', 'skill_domain']

C:\Users\arush\AppData\Local\Temp\ipykernel_10416\3026546231.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include="object").columns.tolist()

In [26]:
for col in text_columns:
    df[col] = df[col].str.strip()

In [27]:
df[text_columns].head()

                              job_title                     company_name                       location scraped_city   role_category experience_raw     salary_raw                                                                                                                    skills_required                                                                             job_description posted_date_raw work_mode   company_size_bucket                                                                                                    job_url data_source  scraped_at  salary_tier   experience_tier primary_city           skill_domain
0                        Data Scientist                            Cisco                      Bengaluru    Bangalore  Data Scientist       7-10 Yrs  Not Disclosed  Computer science, Data analysis, data science, Supply chain operations, data visualization, Customer engagement, cisco, Analytics  Bachelor s degree in Statistics, Mathematics, Computer Science, Data Science, or a rela...    3+ weeks ago   On-site         Large (1000+)              https://www.naukri.com/job-listings-data-scientist-cisco-bengaluru-7-to-10-years-270326504991  naukri.com  2025-06-10  Undisclosed  Senior (6-8 Yrs)    Bangalore  Business Intelligence
1                        Data Scientist                  Caterpillar Inc                      Bengaluru    Bangalore  Data Scientist        4-8 Yrs  Not Disclosed         Basic, Data management, Business analytics, Analytical, Machine learning, Programming, Data processing, data visualization  Requirements Analysis: Knowledge of tools, methods, and techniques of requirement analy...    3+ weeks ago   On-site  Small/Startup (<100)  https://www.naukri.com/job-listings-data-scientist-caterpillar-brazil-bengaluru-4-to-8-years-010526502121  naukri.com  2025-06-10  Undisclosed     Mid (3-5 Yrs)    Bangalore               AI/ML/DL
2              Analytics Data Scientist        Foreign IT Consulting MNC  Hyderabad, Chennai, Bengaluru    Bangalore  Data Scientist        4-9 Yrs  Not Disclosed                                                                                                                      Not Available                                                                               Not Available   Not Available   On-site         Large (1000+)                                                                                                        NaN  naukri.com  2025-06-10  Undisclosed     Mid (3-5 Yrs)    Hyderabad  Business Intelligence
3                        Data Scientist  Fortune 500 IT Services Company              Mumbai, Bengaluru    Bangalore  Data Scientist      10-14 Yrs  Not Disclosed                                                                                                                      Not Available                                                                               Not Available   Not Available   On-site  Small/Startup (<100)                                                                                                        NaN  naukri.com  2025-06-10  Undisclosed           Fresher       Mumbai           Data Science
4  Sr. Artificial Intelligence Engineer    Fortune 500 Product-based MNC                Pune, Bengaluru    Bangalore  Data Scientist       5-10 Yrs  Not Disclosed                                                                                                                      Not Available                                                                               Not Available   Not Available   On-site  Small/Startup (<100)                                                                                                        NaN  naukri.com  2025-06-10  Undisclosed     Mid (3-5 Yrs)         Pune           Data Science

In [28]:
print(type(df["skills_required"].iloc[0]))

<class 'str'>

In [29]:
for i in range(5):
    print(f"Job {i+1}")
    print(df["skills_required"].iloc[i])
    print("-" * 80)

Job 1
Computer science, Data analysis, data science, Supply chain operations, data visualization, Customer engagement, cisco, Analytics
--------------------------------------------------------------------------------
Job 2
Basic, Data management, Business analytics, Analytical, Machine learning, Programming, Data processing, data visualization
--------------------------------------------------------------------------------
Job 3
Not Available
--------------------------------------------------------------------------------
Job 4
Not Available
--------------------------------------------------------------------------------
Job 5
Not Available
--------------------------------------------------------------------------------

In [30]:
print("Missing Skills:", df["skills_required"].isna().sum())

Missing Skills: 0

In [31]:
print("Empty Skill Entries:", (df["skills_required"].str.strip() == "").sum())

Empty Skill Entries: 0

In [32]:
skill_counts = (
    df["skills_required"]
    .str.split(",")
    .apply(len)
)

skill_counts.describe()

count    23201.000000
mean         7.627775
std          1.336385
min          1.000000
25%          8.000000
50%          8.000000
75%          8.000000
max          8.000000
Name: skills_required, dtype: float64

In [33]:
from collections import Counter

all_skills = []

for skills in df["skills_required"]:
    if skills != "Not Available":
        all_skills.extend([skill.strip() for skill in skills.split(",")])

raw_skill_frequency = (
    pd.DataFrame(
        Counter(all_skills).items(),
        columns=["Skill", "Frequency"]
    )
    .sort_values("Frequency", ascending=False)
    .reset_index(drop=True)
)

raw_skill_frequency.head(30)

                      Skill  Frequency
0                    Python       2744
1             Data analysis       2360
2                Analytical       2345
3                       SQL       2306
4                Automation       1935
5          Machine learning       1929
6   Artificial Intelligence       1835
7          Computer science       1687
8                      Data       1615
9                 Analytics       1567
10                   python       1516
11                    Agile       1356
12        Business analysis       1205
13            data analysis       1155
14         Business Analyst       1067
15                      GCP       1013
16         Machine Learning        994
17                   Coding        981
18         Data Engineering        973
19             Data quality        959
20            Data modeling        858
21                      AWS        816
22        business analysis        811
23               Consulting        808
24       Project management        785
25              Development        751
26                    Cloud        745
27       project management        736
28               Management        730
29               Javascript        706

### Normalizing skill spellings

`skills_required` is free text, so the same skill shows up under many spellings — `.Net` / `.NET` / `asp.net` / `ASP.Net`. A handful of raw variants also include stray numbers like `"10635"` and full sentence fragments like `"Business Analyst in IT / digital transformation projects"`.

The pass below does a systematic clean in one place: drop junk tokens, merge case/punctuation variants of the same skill into one canonical label, drop generic non-skill terms and job-title fragments, and drop skills so rare (appearing in only 1-2 of 23,000+ postings) they aren't useful for matching anyway.

This is the **only** place skill cleaning happens in the pipeline — later notebooks reuse `clean_skill_frequency.csv` produced here instead of re-deriving skill counts from scratch.

In [34]:
import re
from collections import Counter, defaultdict

def split_raw(skills_str):
    if pd.isna(skills_str) or skills_str in ("", "Not Available"):
        return []
    return [s.strip() for s in skills_str.split(",") if s.strip() != ""]

raw_token_freq = Counter()
for skills in df["skills_required"]:
    raw_token_freq.update(split_raw(skills))

def is_junk(tok):
    # pure numbers/symbols, e.g. "10635", "277"
    if re.fullmatch(r"[\d.,+%\-]+", tok):
        return True
    # sentence-fragment style entries, not a discrete skill
    if len(tok.split()) > 6:
        return True
    # stray leading-punctuation scrape artifacts
    if tok.startswith(". "):
        return True
    # single stray characters, except real 1-letter language names
    if len(tok) == 1 and tok.upper() not in {"R", "C"}:
        return True
    return False

kept_tokens = {tok for tok in raw_token_freq if not is_junk(tok)}

# Fold case/punctuation variants of the same skill (".Net" / ".NET" / "asp.net") into one canonical label,
# choosing the most frequently occurring original spelling as the display form.
def fold_key(tok):
    return re.sub(r"[^a-z0-9]", "", tok.lower())

groups = defaultdict(list)
for tok in kept_tokens:
    groups[fold_key(tok)].append(tok)

canonical_for = {}
for key, variants in groups.items():
    if key == "":
        continue
    best = max(variants, key=lambda v: raw_token_freq[v])
    for v in variants:
        canonical_for[v] = best

print(f"Raw unique tokens: {len(raw_token_freq)}")
print(f"Kept after junk filter: {len(kept_tokens)}")
print(f"Merged into canonical skills: {len(set(canonical_for.values()))}")

Raw unique tokens: 14337
Kept after junk filter: 14291
Merged into canonical skills: 10429

In [35]:
# Generic concepts / disciplines that aren't a specific tool or technology.
# Matched case-insensitively against the canonical label (see fix below) so casing
# differences in the source data can no longer cause silent misses.
GENERIC_TERMS = {
    "Analytical", "Analysis", "Analytics", "Business Analysis",
    "Project Management", "Data", "Data Management", "Data Processing",
    "Data Modeling", "Data Quality", "Coding", "Programming", "Development",
    "Management", "Consulting", "Cloud", "Architecture", "Operations",
    "Workflow", "Research", "Sales", "Training", "Compliance", "Forecasting",
    "Process Improvement", "Risk Management", "Healthcare", "Computer Science",
    "Business Development", "Customer Service", "Market Research", "Supply Chain",
    "Information Technology", "Lead Generation", "Basic",
}
GENERIC_TERMS_LOWER = {t.lower() for t in GENERIC_TERMS}

# Job-title filter: any canonical skill that IS or ENDS WITH a role word is a title,
# not a technology ("Data Scientist" -> drop; "Data" alone already covered above;
# "Python", "AWS", "Power BI" don't match any of these words, so they're untouched).
# Using \b word boundaries so this won't match inside unrelated words
# (e.g. "Architect" doesn't match "Architecture").
import re

ROLE_WORDS = [
    "Analyst", "Scientist", "Engineer", "Developer", "Manager", "Consultant",
    "Architect", "Administrator", "Specialist", "Executive", "Coordinator",
    "Officer", "Director", "Lead", "Head", "Trainer", "Intern", "Associate",
    "Representative", "Supervisor",
]
ROLE_TITLE_PATTERN = re.compile(r"\b(" + "|".join(ROLE_WORDS) + r")\b", re.IGNORECASE)

# Safety-valve allowlist: canonical skills that would otherwise match ROLE_TITLE_PATTERN
# but are genuine named tools/products, not job titles. Empty today; add entries here
# if a real technology name is ever caught by the pattern.
ROLE_PATTERN_ALLOWLIST = set()

def is_generic_or_title(canon):
    if canon.lower() in GENERIC_TERMS_LOWER:
        return True
    if canon in ROLE_PATTERN_ALLOWLIST:
        return False
    if ROLE_TITLE_PATTERN.search(canon):
        return True
    return False

flagged = {c for c in set(canonical_for.values()) if is_generic_or_title(c)}
print(f"Canonical skills flagged as generic/job-title: {len(flagged)} of {len(set(canonical_for.values()))}")

Canonical skills flagged as generic/job-title: 728 of 10429

In [36]:
# Verify against the exact terms that silently failed before the fix
for skill in [
    "Analytics", "Analytical", "Business Analyst", "Computer Science",
    "Coding", "Data", "Business Analysis", "Project Management",
    "Data Analyst", "Data Scientist",
]:
    canon = canonical_for.get(skill, skill)
    print(f"{skill!r:22s} -> canonical {canon!r:22s} | removed now? {is_generic_or_title(canon)}")

print()
# Spot-check that real technologies are NOT touched
for skill in ["Python", "SQL", "AWS", "Power BI", "Spark", "TensorFlow", "Tableau", "Java"]:
    canon = canonical_for.get(skill, skill)
    print(f"{skill!r:22s} -> canonical {canon!r:22s} | removed now? {is_generic_or_title(canon)}")

'Analytics'            -> canonical 'Analytics'            | removed now? True
'Analytical'           -> canonical 'Analytical'           | removed now? True
'Business Analyst'     -> canonical 'Business Analyst'     | removed now? True
'Computer Science'     -> canonical 'Computer science'     | removed now? True
'Coding'               -> canonical 'Coding'               | removed now? True
'Data'                 -> canonical 'Data'                 | removed now? True
'Business Analysis'    -> canonical 'Business analysis'    | removed now? True
'Project Management'   -> canonical 'Project management'   | removed now? True
'Data Analyst'         -> canonical 'Data Analyst'         | removed now? True
'Data Scientist'       -> canonical 'Data Scientist'       | removed now? True

'Python'               -> canonical 'Python'               | removed now? False
'SQL'                  -> canonical 'SQL'                  | removed now? False
'AWS'                  -> canonical 'AWS'                  | removed now? False
'Power BI'             -> canonical 'power bi'             | removed now? False
'Spark'                -> canonical 'Spark'                | removed now? False
'TensorFlow'           -> canonical 'Tensorflow'           | removed now? False
'Tableau'              -> canonical 'Tableau'              | removed now? False
'Java'                 -> canonical 'Java'                 | removed now? False

In [37]:
def clean_skill_list(skills_str):
    out, seen = [], set()
    for tok in split_raw(skills_str):
        canon = canonical_for.get(tok)
        if canon and not is_generic_or_title(canon) and canon not in seen:
            seen.add(canon)
            out.append(canon)
    return out

cleaned_lists = df["skills_required"].apply(clean_skill_list)

# Drop skills so rare across the corpus (<3 postings out of 23,000+) that they add
# noise to the skill dropdown/summary without being useful for matching.
MIN_FREQ = 3
canonical_freq = Counter(s for lst in cleaned_lists for s in lst)
keep_final = {s for s, freq in canonical_freq.items() if freq >= MIN_FREQ}

df["skills_required"] = cleaned_lists.apply(
    lambda lst: ", ".join(s for s in lst if s in keep_final)
)
df["skills_count"] = df["skills_required"].apply(lambda s: 0 if s == "" else len(s.split(", ")))

print(f"Final unique skills: {len(keep_final)}")
print(f"Jobs left with zero skills after cleaning: {(df['skills_required']=='').sum()} / {len(df)}")
df["skills_required"].head()

Final unique skills: 3771
Jobs left with zero skills after cleaning: 675 / 23201

0    Data analysis, data science, Supply Chain Operations, data visualization, Customer engagement, cisco
1                                                Business analytics, Machine learning, data visualization
2
3
4
Name: skills_required, dtype: str

In [39]:
from collections import Counter

all_skills = []

for skills in df["skills_required"]:
    if skills:
        all_skills.extend(skill.strip() for skill in skills.split(","))

clean_skill_frequency = (
    pd.DataFrame(
        Counter(all_skills).items(),
        columns=["Skill", "Frequency"]
    )
    .sort_values("Frequency", ascending=False)
    .reset_index(drop=True)
)

clean_skill_frequency.head(30)

                          Skill  Frequency
0                        Python       4264
1                 Data analysis       3776
2              Machine learning       3520
3                           SQL       2940
4       Artificial Intelligence       2137
5                    Automation       1995
6                         Agile       1401
7              Data Engineering       1118
8                      power bi       1102
9                           GCP       1061
10                 data science        965
11                          AWS        883
12  Natural Language Processing        876
13                      Pyspark        869
14                   Javascript        852
15                          C++        793
16               data analytics        776
17                           ai        718
18        Business intelligence        689
19                          SAP        688
20                      Backend        681
21                   Monitoring        645
22              Microsoft Azure        620
23             data warehousing        618
24              Troubleshooting        605
25                        Excel        578
26                        MySQL        567
27                       Oracle        560
28                          GIT        549
29                          ERP        545

In [ ]:
clean_skill_frequency.to_csv(
    "../data/processed/clean_skill_frequency.csv",
    index=False
)

np.int64(0)

In [41]:
df["avg_experience"] = (
    df["experience_min_yrs"] +
    df["experience_max_yrs"]
) / 2

In [42]:
df[[
    "experience_min_yrs",
    "experience_max_yrs",
    "avg_experience",
    "skills_required"
]].head()

   experience_min_yrs  experience_max_yrs  avg_experience                                                                                       skills_required
0                 7.0                10.0             8.5  Data analysis, data science, Supply Chain Operations, data visualization, Customer engagement, cisco
1                 4.0                 8.0             6.0                                              Business analytics, Machine learning, data visualization
2                 4.0                 9.0             6.5
3                 0.0                 0.0             0.0
4                 5.0                10.0             7.5

In [43]:
print("=" * 50)
print("FINAL DATASET")
print("=" * 50)

print(f"Rows    : {df.shape[0]:,}")
print(f"Columns : {df.shape[1]}")

==================================================
FINAL DATASET
==================================================
Rows    : 23,201
Columns : 33

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 23201 entries, 0 to 23200
Data columns (total 33 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_id               23201 non-null  int64
 1   job_title            23201 non-null  str
 2   company_name         23201 non-null  str
 3   company_rating       23201 non-null  float64
 4   location             23201 non-null  str
 5   scraped_city         23201 non-null  str
 6   role_category        23201 non-null  str
 7   experience_raw       23201 non-null  str
 8   experience_min_yrs   23201 non-null  float64
 9   experience_max_yrs   23201 non-null  float64
 10  salary_raw           23201 non-null  str
 11  salary_min_lpa       23201 non-null  float64
 12  salary_max_lpa       23201 non-null  float64
 13  salary_disclosed     23201 non-null  bool
 14  skills_required      23201 non-null  str
 15  skills_count         23201 non-null  int64
 16  job_description      23201 non-null  str
 17  posted_date_raw      23201 non-null  str
 18  work_mode            23201 non-null  str
 19  company_size_bucket  23201 non-null  str
 20  job_url              23148 non-null  str
 21  data_source          23201 non-null  str
 22  scraped_at           23201 non-null  str
 23  salary_tier          23201 non-null  str
 24  experience_tier      23201 non-null  str
 25  is_senior            23201 non-null  bool
 26  primary_city         23201 non-null  str
 27  skill_domain         23201 non-null  str
 28  salary_midpoint_lpa  23201 non-null  float64
 29  days_since_posted    23201 non-null  float64
 30  is_fresher_friendly  23201 non-null  bool
 31  salary_negotiable    23201 non-null  bool
 32  avg_experience       23201 non-null  float64
dtypes: bool(4), float64(8), int64(2), str(19)
memory usage: 16.2 MB

In [45]:
missing_values = (
    df.isnull()
      .sum()
      .sort_values(ascending=False)
)

missing_values[missing_values > 0]

job_url    53
dtype: int64

In [46]:
df.to_csv(
    "../data/processed/careerlens_cleaned.csv",
    index=False
)

In [47]:
df["skills_required"].isna().sum()

np.int64(0)

# Conclusion

In this notebook, the raw Indian Technology Jobs dataset was transformed into a clean and standardized dataset ready for analysis.

### Tasks Completed

- Loaded and inspected the raw dataset.
- Verified the dataset for duplicate records and missing values.
- Standardized text fields by removing unnecessary whitespace.
- Inspected and cleaned the `skills_required` column by normalizing inconsistent skill names.
- Preserved existing engineered features provided in the dataset to avoid unnecessary duplication.
- Validated the cleaned dataset to ensure data quality.
- Saved the processed dataset as `careerlens_cleaned.csv`.

### Output

The cleaned dataset has been saved as:

`data/processed/careerlens_cleaned.csv`

This dataset will serve as the single source of truth for all subsequent notebooks and the CareerLens AI application.